[[plugins]]
repo = "folke/noice.nvim"
event = "VeryLazy"
depends = [
  "MunifTanjim/nui.nvim",
  "rcarriga/nvim-notify"
]
hook_add = '''
  require("noice").setup({
    lsp = {
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
        ["cmp.entry.get_documentation"] = true,
      },
      progress = {
        enabled = true,
      },
    },
    messages = {
      enabled = true,
      view = "notify",
      view_error = "notify",
      view_warn = "notify",
      view_history = "messages",
      view_search = "virtualtext",
    },
    cmdline = {
      enabled = true,
      view = "cmdline_popup",
      format = {
        cmdline = { icon = ">" },
        search_down = { icon = "ğŸ”âŒ„" },
        search_up = { icon = "ğŸ”âŒƒ" },
        filter = { icon = "$" },
        lua = { icon = "â˜¾" },
        help = { icon = "?" },
      },
    },
  })
'''

