[[plugins]]
repo = "nvim-tree/nvim-web-devicons"
hook_add = '''
  require('nvim-web-devicons').setup({
    default = true,
    override = {
      fish = {
        icon = "ğŸŸ",
        color = "#428850",
        name = "Fish"
      }
    },
    strict = true,
    color_icons = true,
  })
'''

